### ISSUE TITLE
Add project: OpenAI Scala Client

### ISSUE THREAD

**Issue by peterbanda** [stkeky/best-of-scala#46]
**Project details:**
This is a no-nonsense async Scala client for **OpenAI API** supporting all the available endpoints and params including streaming, the newest ChatGPT completion, voice routines, retries, and other OpenAI-API-compatible providers such as FastChat and Azure.

- Project Name: OpenAI Scala Client
- Github URL: https://github.com/cequence-io/openai-scala-client
- Category:  Libraries for data analysis, machine learning and AI
- License: MIT license 
- Package Managers: maven:io.cequence/openai-scala-client

**Additional context:**

104 stars, Scalafix, Scalafmt, GitHub CI, Scala versions: 2.12, 2.13, 3

**Comment by stkeky** [comment]
@peterbanda Hey, thank you for opening the issue. As @nightscape suggested, you can create a PR per https://github.com/stkeky/best-of-scala/blob/main/CONTRIBUTING.md#add-a-project, and it will be automatically added on the next build. For now, you can use the `sci` category, which is a bit broad, or you can create a new one as @nightscape suggested.

**Comment by peterbanda** [comment]
Hey there, thanx for the feedback! Will create a PR. I am definitely fine with
```
- category: sci
- title: Libraries for data analysis, machine learning and AI
```

Don't feel like starting a new category just for myself :)
