### ISSUE TITLE
Update project: Mill license as MIT

### ISSUE THREAD

**Issue by lolgab** [stkeky/best-of-scala#47]
**Update details:**

Mill always had MIT as its license, but the text format was in a way that Github didn't parse it ad MIT making it appear as unlicensed in the list. I updated the Mill license [here](https://github.com/com-lihaoyi/mill/pull/2657) and now it appears as MIT on Github.

- Project Name:

Mill

**Comment by stkeky** [comment]
@lolgab Thanks for submitting this. 💯 

Since changes are addressed on the Mill repo, they should be automatically pulled on the next build. I'll double-check and close the issue when the next build triggers.

**Comment by stkeky** [comment]
@lolgab It's now displayed correctly. Closing this issue.
