### ISSUE TITLE
Add project: Snowplow

### ISSUE THREAD

**Issue by TLazarevic** [stkeky/best-of-scala#79]
**Project details:**

- Project Name: Snowplow
- Github URL: https://github.com/snowplow/snowplow
- Category:  [Business Intelligence](https://github.com/stkeky/best-of-scala/tree/main#business-intelligence)
- License: 
  Snowplow is copyright 2012-2023 Snowplow Analytics Ltd.
  
  Licensed under the [Apache License, Version 2.0](https://www.apache.org/licenses/LICENSE-2.0) (the "License"); you may not use this software except in compliance with the License.
  
  Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
- Package Managers: / 

**Additional context:** Snowplow is an engine for collecting behavioral data.

**Comment by stkeky** [comment]
@TLazarevic Feel free to create a PR 💯

**Comment by stkeky** [comment]
resolved in #80
